name: Test GDS Course

on:
  push:
    branches: [master]

jobs:
  Test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false

      - name: Set up GDS Env
        shell: bash
        run: |
          conda env create -f https://raw.githubusercontent.com/darribas/gds_env/master/gds_py/gds_py.yml
          conda activate gds
          pip install -r https://github.com/darribas/gds_env/raw/master/gds_py/gds_py_pip.txt

      - name: Check and Log Environment
        shell: bash
        run: |
          conda info
          # Print conda list
          conda list

      - name: Test Blocks
        shell: bash
        continue-on-error: false
        run: |
          make test
